version: "3.8"
services:
  postgres:
    image: postgres:13
    ports:
      - "8000:8000"
    restart: always
    volumes: 
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST_AUTH_METHOD: trust
volumes:
  db_data: